# Generated by Django 6.0.6 on 2026-07-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_curriculumframework_alter_subject_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        # Drop the old constraint first — it references the soon-to-be-removed 'grade' field.
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroom',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='curriculum.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_label',
            field=models.CharField(default='', help_text="Free text: 'Grade 4', 'Year 10', 'Form 4', 'DP2' — whatever this school calls it", max_length=30),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='grade',
        ),
        # Now that grade_label exists and grade is gone, apply the new constraint.
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'grade_label', 'stream', 'academic_year')},
        ),
    ]
