# Generated by Django 6.0.5 on 2026-05-29 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_open', models.BooleanField(default=False)),
                ('review_deadline', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='schools.school')),
            ],
            options={
                'ordering': ['-academic_year', '-term'],
                'unique_together': {('school', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_enjoyment', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much did you enjoy this subject this term? (1=Not much, 5=Loved it)')),
                ('understanding', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well did you understand what was taught? (1=Very confused, 5=Understood everything)')),
                ('teacher_explains_well', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How clearly did your teacher explain things? (1=Hard to follow, 5=Very clear)')),
                ('teacher_encourages', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much did your teacher encourage you to ask questions? (1=Never, 5=Always)')),
                ('real_world_connection', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Did the lessons show you how this subject matters in real life? (1=Not really, 5=Yes, clearly)')),
                ('favourite_thing', models.TextField(blank=True, help_text='What was your favourite thing you learned this term?')),
                ('want_to_learn_more', models.TextField(blank=True, help_text='What would you love to learn more about?')),
                ('suggestion', models.TextField(blank=True, help_text='One thing that would make this subject even better for you?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.teacherassignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.classroom')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.semester')),
            ],
            options={
                'unique_together': {('student', 'semester', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='ParentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.semester')),
            ],
            options={
                'unique_together': {('parent', 'student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SoftSkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reflection', models.TextField(blank=True, help_text='How did you practise this skill this term?')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softskill_ratings', to='reviews.semester')),
                ('soft_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='curriculum.softskill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softskill_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'semester', 'soft_skill')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much of the syllabus did you cover?')),
                ('student_engagement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How engaged were students?')),
                ('values_integration', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well did you integrate life values?')),
                ('highlights', models.TextField(blank=True, help_text='What went really well this term?')),
                ('challenges', models.TextField(blank=True, help_text='What was challenging?')),
                ('next_term_goals', models.TextField(blank=True, help_text='What will you do differently next term?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.classroom')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assessments', to='reviews.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'semester', 'classroom', 'subject')},
            },
        ),
    ]
