# Generated by Django 6.0.5 on 2026-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('primary', 'Primary (Grades 1-6)'), ('junior', 'Junior School (Grades 7-9)'), ('junior', 'Junior School (Grades 7-9)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('is_core', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
